Switch to anticonf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,51 +1,63 @@
 #!/bin/bash
+# Anticonf (tm) script by Jeroen Ooms (2015)
+# This script will query 'pkg-config' for the required cflags and ldflags.
+# If pkg-config is unavailable or does not find the library, try setting
+# INCLUDE_DIR and LIB_DIR manually via e.g:
+# R CMD INSTALL --configure-vars='INCLUDE_DIR=/.../include LIB_DIR=/.../lib'
 
-# Custom include path for compatibility
-if [ "$OPENSSL_INCLUDES" ]; then
-  echo "PKG_CPPFLAGS= -I$OPENSSL_INCLUDES" > src/Makevars
-  echo "PKG_LIBS= -lssl -lcrypto" >> src/Makevars
-  exit 0
-fi
+# Library settings
+PKG_CONFIG_NAME="libssl"
+PKG_DEB_NAME="libssl-dev"
+PKG_RPM_NAME="openssl-devel"
+PKG_CSW_NAME="libssl_dev"
+PKG_TEST_HEADER="<openssl/evp.h>"
+LDFLAGS_DEFAULT="-lssl -lcrypto"
+CFLAGS_DEFAULT=""
 
-# Use backticks to be bourne compliant
+# Use pkg-config if available
 PKGCONFIG=$(command -v pkg-config)
-
-# Try pkg-config first if available
 if [ "$PKGCONFIG" ]; then
-  PKG_CFLAGS=$(pkg-config --cflags libssl)
-  PKG_LIBS=$(pkg-config --libs libssl)
+  PKGCONFIG_CFLAGS=$(pkg-config --cflags ${PKG_CONFIG_NAME})
+  PKGCONFIG_LIBS=$(pkg-config --libs ${PKG_CONFIG_NAME})
 fi
 
-# See if pkg-config succeeded. PKG_CFLAGS can be empty
+# Note that cflags may be empty in case of success
 if [ "$PKG_CFLAGS" ] || [ "$PKG_LIBS" ]; then
-  echo "Using pkg-config cflags and libs"
-elif [ -r "/opt/csw/include/openssl/rand.h" ]; then
-  PKG_CFLAGS="-I/opt/csw/include"
-  PKG_LIBS="-L/opt/csw/lib -lssl -lcrypto"
-elif [ -r "/usr/include/openssl/rand.h" ]; then
-  PKG_CFLAGS="-I/usr/include"
-elif [ -r "/usr/local/include/openssl/rand.h" ]; then
-  PKG_CFLAGS="-I/usr/local/include"
+  echo "Found custom cflags and libs!"
+elif [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]; then
+  echo "Found INCLUDE_DIR and/or LIB_DIR!"
+  PKG_CFLAGS="-I$INCLUDE_DIR $CFLAGS_DEFAULT"
+  PKG_LIBS="-L$LIB_DIR $LDFLAGS_DEFAULT"
+elif [ "$PKGCONFIG_CFLAGS" ] || [ "$PKGCONFIG_LIBS" ]; then
+  echo "Found pkg-config cflags and libs!"
+  PKG_CFLAGS=${PKGCONFIG_CFLAGS}
+  PKG_LIBS=${PKGCONFIG_LIBS}
 else
-  echo "Could not find openssl. Please install libssl-dev (deb) or openssl-devel (rpm)."
-  exit 1
+  PKG_CFLAGS=${CFLAGS_DEFAULT}
+  PKG_LIBS=${LDFLAGS_DEFAULT}
 fi
 
-# Clean Makevars
-echo "# Auto generated by configure" > src/Makevars
+# For debugging
+echo "Using cflags=$PKG_CFLAGS" 1>&2
+echo "Using libs=$PKG_LIBS" 1>&2
 
-# Write cflags to Makevars
-if [ "$PKG_CFLAGS" ]; then
-  echo "PKG_CPPFLAGS= $PKG_CFLAGS" >> src/Makevars
-  echo "Found cflags: $PKG_CFLAGS"
+# Test configuration
+echo "#include $PKG_TEST_HEADER" | cc $PKG_CFLAGS -std=gnu99 -E -xc - >/dev/null 2>&1 || R_CONFIG_ERROR=1;
+
+# Customize the error
+if [ $R_CONFIG_ERROR ]; then
+  echo "------------------------- ANTICONF ERROR ---------------------------" 1>&2
+  echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:" 1>&2
+  echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)" 1>&2
+  echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)" 1>&2
+  echo " * csw: $PKG_CSW_NAME (Solaris)" 1>&2
+  echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your" 1>&2
+  echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config" 1>&2
+  echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:" 1>&2
+  echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'" 1>&2
+  echo "--------------------------------------------------------------------" 1>&2
+  exit 1;
 fi
 
-# Use linker flags if found
-if [ "$PKG_LIBS" ]; then
-  echo "PKG_LIBS= $PKG_LIBS" >> src/Makevars
-  echo "Found ldflags: $PKG_LIBS"
-else
-  echo "PKG_LIBS= -lssl -lcrypto" >> src/Makevars
-fi
-
-exit 0
+# Write to Makevars
+sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" -e "s|@errmsg@|$PKG_ERRMSG|" src/Makevars.in > src/Makevars
